
# 基础镜像
FROM jdk:8

# 作者信息
MAINTAINER "sixkery"

# 添加一个存储空间
VOLUME /tmp

# 暴露端口
EXPOSE 8080

# 添加变量，如果使用 dockerfile-maven-plugin, 则会自动替换这里的变量内容
ARG JAR_FILE=target/code-docker.jar

# 往容器中添加 jar 包
ADD ${JAR_FILE} app.jar

# 启动镜像自动运行程序

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/urandom","-jar","/app.jar"]